title: CardFight Heroes
author: GrabFiend
email: ArmaniBrown28@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Do you want ideas for a new Cardfight deck for Standard or Premium formats? Do you want to get better at decision making? Step no further, this is the website for you!!
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
